# Machine Learning - Deep Learning
***
Using what I learned in the previous machine learning models, I am now going to try Deep Learning with Keras.  As discussed in previous model tests, `Targets by raw counts` worked best for regression.  As such, I will be using the appropriate dataset for the Regression Deep Learning Model

In [108]:
# Import Tools

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from keras.layers import Dense
from keras.models import Sequential
from keras.optimizers import SGD
from keras.callbacks import EarlyStopping
from sklearn.preprocessing import StandardScaler
from keras.utils import to_categorical

# Make plots pretty
sns.set()

In [2]:
# Read in Data
df = pd.read_csv('Combo_Cleaned.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)
df.head()

,cfc,state,county,0-17,18-25,26-34,35-44,45-54,55-64,65+,...,platinum,gold,silver,bronze,catastrophic,new,active_renew,auto_renew,tps,Year
0,12109,FL,St. Johns County,1259.0,1093.0,1566.0,1684.0,2354.0,2963.0,41.0,...,1128.0,594.0,7209.0,1967.0,62.0,5875.0,3783.0,1302.0,10960.0,2015
1,10001,DE,Kent County,413.0,284.0,529.0,530.0,771.0,872.0,18.0,...,107.0,528.0,2136.0,629.0,17.0,1853.0,655.0,909.0,3417.0,2015
2,10003,DE,New Castle County,1964.0,1275.0,2487.0,2333.0,3288.0,3494.0,126.0,...,679.0,2406.0,8835.0,2943.0,104.0,7453.0,3340.0,4174.0,14967.0,2015
3,10005,DE,Sussex County,794.0,436.0,805.0,929.0,1453.0,2204.0,30.0,...,257.0,1144.0,4198.0,1032.0,20.0,3408.0,1531.0,1712.0,6651.0,2015
4,12001,FL,Alachua County,726.0,2161.0,2734.0,1867.0,2250.0,2940.0,41.0,...,1188.0,429.0,9169.0,1848.0,85.0,6443.0,4378.0,1898.0,12719.0,2015

In [17]:
# Create our X and y for the model with individual y's for each metallic tier.

# Our X Dropping the Metallic Tier Targets, String Data, and Categorical Year
X = df.drop(['cfc','state','county','platinum','gold','silver','bronze','catastrophic', 'Year',
             'tps'], axis=1).values

# Get shape of predictors
n_cols = X.shape[1]

# Individual y's for Each Target Data
ycat = df.catastrophic.valuestype
ybro = df.bronze.values
ysil = df.silver.values
ygold = df.gold.values
yplat = df.platinum.values

# Create List of Target Values and Names of Target Values
ys=[ycat, ybro, ysil, ygold, yplat]
ys_name = ['Catastrophic','Bronze','Silver','Gold','Platinum']

In [64]:
# Define model creation program.

def make_model(input_shape = (n_cols,)):
    model = Sequential()
    model.add(Dense(100, activation='relu', input_shape=input_shape))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1))
    return(model)

# Create Early Stopping monitor
monitor = EarlyStopping(patience=3)

In [65]:
make_model()
ss = StandardScaler()
Xs = ss.fit_transform(X)
model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(Xs, ysil,validation_split=.3, epochs=5, batch_size=128)

Train on 3175 samples, validate on 1361 samples
Epoch 1/5
3175/3175 [==============================] - 2s 737us/step - loss: nan - val_loss: nan
Epoch 2/5
3175/3175 [==============================] - 1s 198us/step - loss: nan - val_loss: nan
Epoch 3/5
3175/3175 [==============================] - 1s 218us/step - loss: nan - val_loss: nan
Epoch 4/5
3175/3175 [==============================] - 1s 203us/step - loss: nan - val_loss: nan
Epoch 5/5
3175/3175 [==============================] - 1s 217us/step - loss: nan - val_loss: nan

In [39]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_32 (Dense)             (None, 500)               16000
_________________________________________________________________
dense_33 (Dense)             (None, 500)               250500
_________________________________________________________________
dense_34 (Dense)             (None, 500)               250500
_________________________________________________________________
dense_35 (Dense)             (None, 1)                 501
=================================================================
Total params: 517,501
Trainable params: 517,501
Non-trainable params: 0
_________________________________________________________________

In [109]:
# Read in Data
dfp = pd.read_csv('Combo_Percents.csv')
dfp.drop('Unnamed: 0', axis=1, inplace=True)
dfp.head()

,cfc,state,county,0-17,18-25,26-34,35-44,45-54,55-64,65+,...,platinum,gold,silver,bronze,catastrophic,new,active_renew,auto_renew,tps,Year
0,12109,FL,St. Johns County,1259.0,1093.0,1566.0,1684.0,2354.0,2963.0,41.0,...,0.10,0.05,0.66,0.18,0.01,5875.0,3783.0,1302.0,10960.0,2015
1,10001,DE,Kent County,413.0,284.0,529.0,530.0,771.0,872.0,18.0,...,0.03,0.15,0.63,0.18,0.00,1853.0,655.0,909.0,3417.0,2015
2,10003,DE,New Castle County,1964.0,1275.0,2487.0,2333.0,3288.0,3494.0,126.0,...,0.05,0.16,0.59,0.20,0.01,7453.0,3340.0,4174.0,14967.0,2015
3,10005,DE,Sussex County,794.0,436.0,805.0,929.0,1453.0,2204.0,30.0,...,0.04,0.17,0.63,0.16,0.00,3408.0,1531.0,1712.0,6651.0,2015
4,12001,FL,Alachua County,726.0,2161.0,2734.0,1867.0,2250.0,2940.0,41.0,...,0.09,0.03,0.72,0.15,0.01,6443.0,4378.0,1898.0,12719.0,2015

In [133]:
# Create the X and y for the model with individual y's for each metallic tier.

# Our X Dropping the Metallic Tier Targets, String Data, Categorical Year, and TPS
Xp = dfp.drop(['cfc','state','county','platinum','gold','silver','bronze','catastrophic', 'Year',
               'tps'],axis=1).values

# Individual y's for Each Target Data
ycatp = (dfp.catastrophic.values * 100).astype(int)
ybrop = (dfp.bronze.values *100).astype(int)
ysilp = (dfp.silver.values * 100).astype(int)
ygoldp = (dfp.gold.values * 100).astype(int)
yplatp = (dfp.platinum.values * 100).astype(int)

# Get shape of predictors
n_cols_class = Xp.shape[1]

# Create List of Target Values for Percent Data
ysp=[ycatp, ybrop, ysilp, ygoldp, yplatp]

In [134]:
# Define program that converts target percents of TPS to categorical numbers
def convert(target):
    '''Takes array from 0 - 100 and converts it to categories representing batches of 5'''
    for n in range(len(target)):
        if target[n] in np.arange(0,5):
            target[n] = 0
        if target[n] in np.arange(5,10):
            target[n]=1
        if target[n] in np.arange(10,15):
            target[n] = 2
        if target[n] in np.arange(15,20):
            target[n]=3
        if target[n] in np.arange(20,25):
            target[n] = 4
        if target[n] in np.arange(25,30):
            target[n]=5
        if target[n] in np.arange(30,35):
            target[n] = 6
        if target[n] in np.arange(35,40):
            target[n]=7
        if target[n] in np.arange(40,45):
            target[n]=8
        if target[n] in np.arange(45,50):
            target[n] = 9
        if target[n] in np.arange(50,55):
            target[n] = 10
        if target[n] in np.arange(55,60):
            target[n]=11
        if target[n] in np.arange(60,65):
            target[n] = 12
        if target[n] in np.arange(65,70):
            target[n]=13
        if target[n] in np.arange(70,75):
            target[n] = 14
        if target[n] in np.arange(75,80):
            target[n]=15
        if target[n] in np.arange(80,85):
            target[n] =16
        if target[n] in np.arange(85,90):
            target[n]=17
        if target[n] in np.arange(90,95):
            target[n]=18
        if target[n] in np.arange(95,101):
            target[n]=19

In [135]:
# Define model creation program.
def make_model_class(predictor, input_shape = (n_cols_class,)):
    model = Sequential()
    model.add(Dense(100, activation='relu', input_shape=input_shape))
    model.add(Dense(100, activation='relu'))
    model.add(Dense(100, activation='relu'))
    model.add(Dense(len(np.unique(predictor)), activation='softmax'))
    return(model)

# Create Early Stopping monitor
monitor = EarlyStopping(patience=3)

In [136]:
# Convert Catastrophic Tier to Binned Categories
convert(ycatp)

In [141]:
# Test Classification Model on Catastrophic Dataset
test = ycatp/10
make_model_class(predictor=ycatp)
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(Xp, test,validation_split=.3, epochs=10, callbacks=[monitor])

Train on 3172 samples, validate on 1360 samples
Epoch 1/10
3172/3172 [==============================] - 5s 1ms/step - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
Epoch 2/10
 320/3172 [==>...........................] - ETA: 1s - loss: nan - acc: 0.0000e+00

C:\ProgramData\Anaconda3\lib\site-packages\keras\callbacks.py:538: RuntimeWarning: invalid value encountered in less
  if self.monitor_op(current - self.min_delta, self.best):

3172/3172 [==============================] - 2s 642us/step - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
Epoch 3/10
3172/3172 [==============================] - 2s 580us/step - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00

In [143]:
np.unique(test)

array([ 0. ,  0.1])